# Generated by Django 3.2 on 2021-04-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_productsfeedbacks_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsfeedbacks',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
