# Generated by Django 3.1.8 on 2021-04-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210420_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='users',
        ),
    ]
