# Generated by Django 3.1.8 on 2021-04-22 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_remove_order_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='check_me_out',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(blank=True, to='main.Cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.checkout'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
