# Generated by Django 3.2 on 2021-05-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210518_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('BLACK', 'BLACK'), ('ORANGE', 'ORANGE'), ('PINK', 'PINK'), ('PURPLE', 'PURPLE'), ('GREEN', 'GREEN'), ('YELLOW', 'YELLOW'), ('GRAY', 'GRAY'), ('WHITE', 'WHITE')], max_length=50),
        ),
    ]
