# Generated by Django 3.2 on 2021-05-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_contactus_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
