# Generated by Django 3.1.8 on 2021-06-11 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210606_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
